services:
  api:
    image: ghcr.io/gurrming/be-goorm-project/backend:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "0000"
      JWT_SECRET: dev-secret-change-me
      TZ: Asia/Seoul

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: app
      TZ: Asia/Seoul
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
