services:
  api:
    image: ghcr.io/gurrming/backend:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: app
      TZ: Asia/Seoul
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
