global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'heartbit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 로컬 실행 시 Docker에서 내 PC로 접근하는 주소