pluginManagement {
    repositories {
        gradlePluginPortal()
        google() // 추가
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google() // 추가
        mavenCentral()
    }
}

rootProject.name = 'heartbit'

