-- V1__init.sql

-- [추가됨] 0. ID 컬럼의 잠금 장치 해제 (ALWAYS -> BY DEFAULT)
-- 이렇게 해야 사람이 수동으로 ID를 수정할 수 있습니다.
ALTER TABLE category ALTER COLUMN category_id SET GENERATED BY DEFAULT;

-- 1. news_data 테이블 생성
CREATE TABLE IF NOT EXISTS news_data (
                                         news_id BIGSERIAL PRIMARY KEY,
                                         category_id BIGINT NOT NULL,
                                         title TEXT NOT NULL,
                                         content TEXT,
                                         url TEXT,
                                         sentiment VARCHAR(20),
                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 기존 ID 밀어내기
UPDATE category SET category_id = category_id + 10000;

-- 3. 임시 매핑 테이블로 재정렬
CREATE TEMP TABLE category_reorder_map AS
SELECT
    symbol,
    row_number() OVER (ORDER BY category_id ASC) AS new_id
FROM category;

-- 4. 실제 category 테이블 업데이트 (1번부터 다시 매기기)
UPDATE category c
SET category_id = m.new_id
FROM category_reorder_map m
WHERE c.symbol = m.symbol;

-- 5. 시퀀스 리셋 (마지막 번호 다음부터 자동 증가하도록)
SELECT setval(pg_get_serial_sequence('category', 'category_id'), (SELECT MAX(category_id) FROM category));

-- 6. 외래키 연결
ALTER TABLE news_data
    DROP CONSTRAINT IF EXISTS fk_category_news;

ALTER TABLE news_data
    ADD CONSTRAINT fk_category_news
        FOREIGN KEY (category_id)
            REFERENCES category(category_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE;

-- 7. 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_news_category_id ON news_data(category_id);